### ISSUE TITLE
`--help` does not print anything

### ISSUE THREAD

**Issue by phil-opp** [dan-t/rusty-release#5]
There is no output for `rusty-release --help` for version 0.6.0.

**Comment by dan-t** [comment]
Strange, looks like some changes in the behavior of `clap`.

Whatever, should be fixed with `rusty-release 0.6.1`.

**Comment by phil-opp** [comment]
Wow, that was fast! Thanks a lot for the fix and the awesome tool in general!

**Comment by dan-t** [comment]
Oh, nice to hear. Thank you!
