### ISSUE TITLE
Bumps unrelated dependency version on release

### ISSUE THREAD

**Issue by phil-opp** [dan-t/rusty-release#6]
Rusty-release seems to not only increase the version number of the crate, but also equal version numbers of dependencies. Example: https://github.com/rust-osdev/bootimage/commit/e159e4095ca03826a5b366b1cf528804a06bf6bc#diff-80398c5faae3c069e4e6aa2ed11b28c0R17 (the cargo-metadata dependency was also bumped to 0.6.4).

**Comment by dan-t** [comment]
If you want to create a pull request, by changing in line 73 of `cargo_proj.rs` the call
of `String::replace` with `String::replacen` and using a `count` of `1`, please go on.

**Comment by phil-opp** [comment]
Thanks for the pointer! I created #7 to fix this.
